version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 51773
      - 52773:52773
      - 53773
    volumes:
      - ./:/irisdev/app
      - ./data:/opt/irisapp/dataImport
      - ./src/csp:/opt/irisapp/csp
       